dir=$(PWD)

CC = arm-none-eabi-gcc

# Flags - C Language Options
CFLAGS += -ffreestanding --specs=nosys.specs -mthumb -mcpu=cortex-m0
CFLAGS += -std=c99 -mlittle-endian
CFLAGS += -I inc

.PHONY: all
all: 
	$(CC) $(CFLAGS) main.c -o output

clean:
	rm *.o